
2023-11-21 23:11:00,733 INFO: errors [in /Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/app.py:506]
2023-11-21 23:11:52,740 ERROR: Exception on /artists/4 [GET] [in /usr/local/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/app.py", line 349, in show_artist
    return render_template('pages/show_artist.html', artist=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/templates/pages/show_artist.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/templates/layouts/main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/templates/pages/show_artist.html", line 68, in block 'content'
    <h6>{{ show.start_time|datetime('full') }}</h6>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/app.py", line 65, in format_datetime
    date = dateutil.parser.parse(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser.py", line 587, in parse
    if (isinstance(tzinfos, collections.Callable) or
                            ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
2023-11-21 23:12:06,937 ERROR: Exception on /venues/1 [GET] [in /usr/local/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/app.py", line 210, in show_venue
    return render_template('pages/show_venue.html', venue=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/templates/pages/show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/templates/layouts/main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/templates/pages/show_venue.html", line 71, in block 'content'
    <h6>{{ show.start_time|datetime('full') }}</h6>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/app.py", line 65, in format_datetime
    date = dateutil.parser.parse(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser.py", line 587, in parse
    if (isinstance(tzinfos, collections.Callable) or
                            ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
2023-11-21 23:12:14,397 ERROR: Exception on /shows [GET] [in /usr/local/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/app.py", line 469, in shows
    return render_template('pages/shows.html', shows=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/templates/pages/shows.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/templates/layouts/main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/templates/pages/shows.html", line 9, in block 'content'
    <h4>{{ show.start_time|datetime('full') }}</h4>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/app.py", line 65, in format_datetime
    date = dateutil.parser.parse(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser.py", line 587, in parse
    if (isinstance(tzinfos, collections.Callable) or
                            ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
2023-11-21 23:23:41,998 INFO: errors [in /Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/app.py:513]
2023-11-21 23:24:10,000 INFO: errors [in /Users/josesmac/Fullstack_Projects/Udacity_FS_nano/Course_Projects/fyurr/app.py:513]
